### ISSUE TITLE
Game crashes when selecting a replicant

### ISSUE THREAD

**Issue by Terryxtl** [onimp/oni_multiplayer#122]
Whenever the host select a replicant during the gameplay, other players encounter a game crash.

**Comment by Terryxtl** [comment]
The replicants every player can see is also different:(

**Comment by zuev93** [comment]
Hi @Terryxtl be aware that the feature that syncs bioprinter has not been released yet (even though that #30 is closed).

So if you have built the mod by yourself - could you provide your player.log from client and host?
Otherwise please bear with us for next release which will contain this feature.

**Comment by zuev93** [comment]
Closing issue since #30 has been released in https://github.com/onimp/oni_multiplayer/releases/tag/v0.4.0-alpha
