### ISSUE TITLE
Sync building side screens (user menu on the right). E.g. selecting filtered item, setting production queue, setting battery levels, etc.

### ISSUE THREAD

**Issue by zuev93** [onimp/oni_multiplayer#92]
See for exhaustive list
https://docs.google.com/spreadsheets/d/1klx2C6pbsQOD0CR1RiFPcvWsTv19xBcj5wd-Q-nI4YA/edit#gid=1436570526

Important:
Add default clause to catch not handled side screens and log them, to be able to track desync errors.

**Comment by polycone** [comment]
Seems like we have to sync individual screens data, because a side screen is a singleton and has a selectable target. This implicates if there's a side screen opened and the target object is being changed the side screen should be updated as well. Maybe it's a subject to change, but I don't see any generalizing options since each side screen has its own data.

**Comment by zuev93** [comment]
Most of the sidescreens (56 out of 69 ) are synced except few left overs (created #169 to cover them).
